# Generated by Django 3.2 on 2022-08-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Productsas', 'verbose_name_plural': 'Products'},
        ),
    ]
