# Generated by Django 3.2 on 2022-08-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
